### ISSUE TITLE
Add option to observe for function calls

### ISSUE THREAD

**Issue by DavidArayan** [Plattar/context-messenger#2]
## About

Currently, when using the context messenger to call a function there is no way for an outside party to know or observe the calls. This change allows adding an observer or listener to custom function calls.

## Proposal

We propose adding the following interface to messenger. There are no limits to the number of observers per function. Caution must be taken to ensure infinite loops do not occur.

- `functionName` - The name of the function to observe as a string
- `callback` - The callback function that accepts `CallbackData` structure type
- - `type` - the type of function callback, `call` when function is called and `return` when function is returned
- - `state` - If the function executed successfully or not
- - `data` - The arguments (if any) that the function returned upon execution

```typescript
interface CallbackData {
    readonly type: "call" | "return";
    readonly state: "success" | "exception";
    readonly data: any;
}

// add a new listener instance to the observer
Plattar.messenger.observer.subscribe(functionName:string, callback: (data:CallbackData): void) : () => boolean;

// remove an existing listener instance from the observer
Plattar.messenger.observer.unsubscribe(functionName:string, callback: (data:CallbackData): void): boolean;
```

- To observe when a function named `sum` has been called and successfully returns `CallbackData` type

```javascript
const callback = (data) => {
    // sum executed, observe the Data for more info
};
```

```javascript
const subscriber:Function = Plattar.messenger.observer.subscribe("sum", callback);
```

- To remove an existing observer from `sum` call the following function

```javascript
const isSuccess:boolean = Plattar.messenger.observer.unsubscribe("sum", callback);
```

- An existing observer can also be removed from the returned function of `subscribe`

```javascript
// add a new listener
const subscriber: Function = Plattar.messenger.observer.subscribe("sum", callback);

// remove an existing listener - same as calling Plattar.messenger.observer.unsubscribe("sum", callback);
const isSuccess:boolean = subscriber();
```

**Comment by calrk** [comment]
Looks good to me
